export declare type status = '' | 'success' | 'warning' | 'info' | 'error'
export declare type position =
    ''
    | 'top'
    | 'bottom'
    | 'center'
    | 'left-top'
    | 'right-top'
    | 'left-bottom'
    | 'right-bottom'
